# build stage
FROM golang:1.12.6-alpine3.9 AS build-env
MAINTAINER zhongfox <zhongfox@gmail.com>
ADD . /src
RUN cd /src && go build -o goapp

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/goapp /app/
ENTRYPOINT ./goapp
