FROM ruby:2.6.3
MAINTAINER zhongfox <zhongfox@gmail.com>

#RUN apt-get update && \
#    apt-get install -y net-tools

# Install gems
ENV APP_HOME /app
ENV HOME /root
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile $APP_HOME/
#COPY Gemfile* $APP_HOME/
RUN bundle install

# Upload source
COPY ./recommend.rb $APP_HOME

# Start server
CMD ["ruby", "recommend.rb"]
