apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: discount
  namespace: fox
spec:
  hosts:
    - "discount.base.svc.cluster.local"
  http:
    - match:
        - headers:
            cookie:
              exact: "user=fox"
      route:
        - destination:
            host: discount.fox.svc.cluster.local
    - route:
        - destination:
            host: discount.base.svc.cluster.local
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: products
  namespace: fox
spec:
  hosts:
    - "products.base.svc.cluster.local"
  http:
    - match:
        - sourceLabels:
            env: fox
      route:
        - destination:
            host: products.fox.svc.cluster.local
    - route:
        - destination:
            host: products.base.svc.cluster.local

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: favorites
  namespace: fox
spec:
  hosts:
    - favorites.base.svc.cluster.local
  http:
    - match:
        - sourceLabels:
            env: fox
      route:
        - destination:
            host: favorites.fox.svc.cluster.local
---
