apiVersion: v1
kind: Namespace
metadata:
  name: fox
  labels:
    istio-injection: enabled
spec:
  finalizers:
    - kubernetes
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: recommend
    version: v2
  name: recommend-v2
  namespace: fox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend
      version: v2
  template:
    metadata:
      labels:
        app: recommend
        version: v2
        env: fox
    spec:
      containers:
        - image: tcmdemo/recommend:v2
          imagePullPolicy: Always
          name: recommend
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: recommend
  name: recommend
  namespace: fox
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: recommend
  type: ClusterIP
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommend
  namespace: fox
spec:
  hosts:
    - "recommend.base.svc.cluster.local"
  http:
    - match:
        - headers:
            cookie:
              exact: "user=fox"
      route:
        - destination:
            host: recommend.fox.svc.cluster.local
            #subset: v1 # todo
            port:
              number: 7000
    - route: # 不能省略todo
        - destination:
            host: recommend.base.svc.cluster.local
            #subset: v1 # todo
            port:
              number: 7000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: scores
    version: v2
  name: scores-v2
  namespace: fox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scores
      version: v2
  template:
    metadata:
      labels:
        app: scores
        version: v2
        env: fox
    spec:
      containers:
        - image: tcmdemo/scores:v2
          imagePullPolicy: Always
          name: scores
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: scores
  name: scores
  namespace: fox
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: scores
  type: ClusterIP
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: scores
  namespace: fox
spec:
  hosts:
    - "scores.base.svc.cluster.local"
  http:
    - match:
        - sourceLabels:
            env: fox
      route:
        - destination:
            host: scores.fox.svc.cluster.local
            #subset: v1 # todo
            port:
              number: 7000
    - route:
        - destination:
            host: scores.base.svc.cluster.local
            #subset: v1 # todo
            port:
              number: 7000
---
