apiVersion: v1
kind: Namespace
metadata:
  name: fox
  labels:
    istio-injection: enabled
spec:
  finalizers:
    - kubernetes
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: discount
    version: v2
  name: discount-v2
  namespace: fox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount
      version: v2
  template:
    metadata:
      labels:
        app: discount
        env: fox
        version: v2
    spec:
      containers:
        - image: tcmdemo/discount:v2
          imagePullPolicy: Always
          name: discount
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: discount
  name: discount
  namespace: fox
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: discount
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: products
    version: v2
  name: products-v2
  namespace: fox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      version: v2
  template:
    metadata:
      labels:
        app: products
        env: fox
        version: v2
    spec:
      containers:
        - image: tcmdemo/products:v2
          imagePullPolicy: Always
          name: products
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: products
  name: products
  namespace: fox
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: products
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: favorites
    version: v1
  name: favorites-v1
  namespace: fox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites
      version: v1
  template:
    metadata:
      labels:
        app: favorites
        env: fox
        version: v1
    spec:
      containers:
        - image: tcmdemo/favorites:v1
          imagePullPolicy: Always
          name: favorites
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: favorites
  name: favorites
  namespace: base
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: favorites
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: favorites
  name: favorites
  namespace: fox
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: favorites
  type: ClusterIP
