apiVersion: v1
kind: Namespace
metadata:
  name: jason
  labels:
    istio-injection: enabled
spec:
  finalizers:
    - kubernetes
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: recommend
    version: v2
  name: recommend-v2
  namespace: jason
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend
      version: v2
  template:
    metadata:
      labels:
        app: recommend
        version: v2
        env: jason
    spec:
      containers:
        - image: tcmdemo/recommend:v2
          imagePullPolicy: IfNotPresent
          name: recommend
          ports:
            - containerPort: 7000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: recommend
  name: recommend
  namespace: jason
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: recommend
  type: ClusterIP
