apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mall
  namespace: base
spec:
  hosts:
    - "*"
  gateways:
    - mall-gateway
  http:
    - route:
        - destination:
            host: mall
            subset: v1
          weight: 50
        - destination:
            host: mall
            subset: v2
          weight: 50
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mall
  namespace: base
spec:
  host: mall
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
